name: fruithub
description: "An ecommerce app for selling and buying fruits."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Core
  equatable: ^2.0.7
  get_it: ^8.2.0
  dartz: ^0.10.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Firebase Services
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  firebase_analytics: ^12.0.2
  firebase_messaging: ^16.0.2
  firebase_crashlytics: ^5.0.2
  firebase_database: ^12.0.2
  firebase_in_app_messaging: ^0.9.0+2
  firebase_app_installations: ^0.4.0+2
  firebase_remote_config: ^6.0.2
  firebase_performance: ^0.11.1

  # State Management
  provider: ^6.1.5+1
  riverpod: ^3.0.1
  get: ^4.7.2
  flutter_bloc: ^9.1.1

  # API Integration
  http: ^1.5.0
  dio: ^5.9.0

  # UI Packages
  flutter_svg: ^2.2.1
  modal_bottom_sheet: ^3.0.0
  persistent_bottom_nav_bar: ^6.2.1
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1
  animations: ^2.0.11
  smooth_page_indicator: ^1.2.1
  flutter_slidable: ^4.0.3
  fluttertoast: ^9.0.0
  flutter_spinkit: ^5.2.2
  lottie: ^3.3.2
  pin_code_fields: ^8.0.1
  country_code_picker: ^3.4.0

  # Local Storage
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  hive: ^2.2.3

  # Notifications and Backgrounds
  flutter_local_notifications: ^19.4.2
  workmanager: ^0.9.0+3
  awesome_notifications: ^0.10.1

  # Utility and Helpers
  connectivity_plus: ^7.0.0
  path_provider: ^2.1.5
  image_cropper: ^11.0.0
  file_picker: ^10.3.3
  image_picker: ^1.2.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  device_info_plus: ^12.1.0
  package_info_plus: ^9.0.0
  logger: ^2.6.1

  # Navigation and Routing
  go_router: ^16.2.4

  # Analytics and Crash Reporting
  sentry_flutter: ^9.6.0

  # Others
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.13.1
  flutter_webview_plugin: ^0.4.0
  flutter_inappwebview: ^6.1.5
  rive: ^0.13.20
  # intl_phone_field: ^3.2.0
  # country_picker: ^2.0.27
  # flutter_otp_text_field: ^1.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/notifications/
    - assets/images/onboarding/
    - assets/images/payments/
    - assets/images/products/
    - assets/images/profile/
    - assets/images/search/
    - assets/images/splash/